Rewrite app
tkachukivan/asp.net-learning-project-contacts-manager pull request #1
Opened 2018-11-14 08:05 UTC by tkachukivan

2018-11-15 20:27 UTC, ayerlashov-gd requested changes
Eliminate unnecessary namespace imports (usings)

Ideally every tier (PL, BLL, DAL) should have its own set of data types, even if some of them are the structurally the same. Automapper is commonly used to map between them and avoid boilerplate. but you may write hand-coded maps right now, 
You should add Contact type to both BLL, and PL and map between them, rather than passing around a DAL type. And don't forget to remove the reference to DAL project from WebAPI project.

Some may disagree with this, but use "var" whenever possible, it improves readability.

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerBL/ContactsManager.cs
> +        private ContactsProvider _contactProvider = new ContactsProvider();
I recommend making this a read-only property, i.e. private ContactsProvider ContactProvider { get; } = new ContactsProvider();
Properties are easier to debug, since you can place a break point.
Read-only makes sense because the provider shouldn't be changed during the lifetime of the manager.

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerDAL/DBConnection.cs
> +            // Open the database connection with retries
This comment is incorrect and redundant

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerDAL/DBConnection.cs
> +    class DBConnection
Use explicit internal scope modifier
Make static

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerDAL/DBConnection.cs
> +                SqlConnectionStringBuilder sb = new SqlConnectionStringBuilder(connStr);
Why do you need the builder?

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerDAL/ContactsProvider.cs
> +                            c.Id = reader.GetGuid(0);
Using constant column indices is not a good practice.
Use column names to get indices.

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerDAL/ContactsProvider.cs
> +                    cmd.CommandText = @"getContacts";
No need for verbatim string

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerDAL/ContactsProvider.cs
> +                using (SqlCommand cmd = conn.CreateCommand())
You can stack usings to reduce nesting

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerDAL/ContactsProvider.cs
> +                            var c = new Contact();
Use a more descriptive name for variable, i.e. 'contact'.
You can use initializer block here.

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/Controllers/ContactsController.cs
> +        private ContactsManager _contactManager = new ContactsManager();
Same comment as in manager for provider field

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/App_Start/WebApiConfig.cs
> +
You're not using attribute routing, but ok

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/App_Start/WebApiConfig.cs
>      {
Not sure why you need this

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/App_Start/RouteConfig.cs
>              routes.MapRoute(
static

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/App_Start/RouteConfig.cs
>              routes.MapRoute(
Make static

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/App_Start/RouteConfig.cs
>              routes.MapRoute(
You don't need this file, you're not using ASP.NET MVC

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/App_Start/RouteConfig.cs
>              routes.MapRoute(
I don't think you need this file nor the route registration, since you're not using ASP.NET MVC

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/App_Start/FilterConfig.cs
>  {
Make static

2018-11-15 20:27 UTC, ayerlashov-gd commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/Global.asax.cs
> +            AreaRegistration.RegisterAllAreas();
Don't need this. Areas are an MVC concept

2018-11-30 07:16 UTC, ayerlashov-gd reviewed
I'm pretty sure there is an overload that onl requires the target type to be specified

2018-11-30 07:16 UTC, ayerlashov commented on ContactsManagerBackend/ContactsManager/ContactsManagerBL/ContactsManager.cs
> +            var contacts = MappingDto.Mapper.Map<List<ContactDto>, List<ContactModel>>(ContactsProvider.GetContacts());
I'm pretty sure there is an overload that onl requires the target type to be specified

2018-11-30 07:18 UTC, ayerlashov-gd reviewed
You can convert this to an expression bodied method

2018-11-30 07:18 UTC, ayerlashov commented on ContactsManagerBackend/ContactsManager/ContactsManagerBL/ContactsManager.cs
> +        public List<ContactModel> GetContacts()
You can convert this to an expression bodied method

2018-11-30 07:56 UTC, ayerlashov-gd approved these changes
Rename Contact types to "Contact". Model and Dto are not usefully descriptive suffixes

2018-11-30 07:56 UTC, ayerlashov commented on ContactsManagerBackend/ContactsManager/ContactsManagerBL/ContactsManager.cs
> +        public List<ContactModel> GetContacts()
You can convert this to an expression bodied method

2018-11-30 07:56 UTC, ayerlashov commented on ContactsManagerBackend/ContactsManager/ContactsManagerBL/ContactsManager.cs
> +            var contacts = MappingDto.Mapper.Map<List<ContactDto>, List<ContactModel>>(ContactsProvider.GetContacts());
I'm pretty sure there is an overload that only requires the target type to be specified

2018-11-30 07:56 UTC, ayerlashov commented on ContactsManagerBackend/ContactsManager/ContactsManagerBL/MappingDto.cs
> +            var config = new MapperConfiguration(cfg => cfg.CreateMap<ContactDto, ContactModel>());
Use static Automapper configuration.

2018-11-30 07:56 UTC, ayerlashov commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/Models/MappingModel.cs
> +            var config = new MapperConfiguration(cfg => cfg.CreateMap<Contact, ContactModel>());
Use static configuration

2018-11-30 07:56 UTC, ayerlashov commented on ContactsManagerBackend/ContactsManager/ContactsManagerWebApi/Controllers/ContactsController.cs
> +            return Ok(ContactsManager.GetContacts());
You forgot to map to PL contact type

2018-12-02 12:19 UTC, merged